#!/usr/bin/env python
"""Regenerate configs/*.json and docs/SIZING.md from the code (analytic; no GPU needed)."""
import json
import os

from h3turbo.bench import GPUS, estimate
from h3turbo.config import make_config, tier_names

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CASES = [("512x320, 4 s", 512, 320, 4.0), ("768x432, 4 s", 768, 432, 4.0)]
STEPS = 4
CARDS = ["rtx3050-4gb", "rtx3050-6gb", "rtx3050-8gb", "rtx3060-12gb", "rtx4090-24gb"]


def main():
    os.makedirs(os.path.join(ROOT, "configs"), exist_ok=True)
    os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
    lines = [
        "# Sizing (generated by `scripts/gen_docs.py`)",
        "",
        "Analytic plan, **not a measurement**: parameter counts and FLOPs are exact counts of the code; "
        "GPU memory is weights + a per-layer activation estimate + 0.8 GB headroom. No GPU was available "
        "when this was generated, so no timings are given. Run `h3turbo bench --ckpt ... --measure` on your card.",
        "",
        "AdaLN parameters are cached per sampling schedule and kept on the CPU, so they are excluded from GPU memory.",
        "",
        "## Parameters",
        "",
        "| tier | transformer total | on GPU (no AdaLN) | AdaLN (CPU) | text enc. | video VAE |",
        "|---|---|---|---|---|---|",
    ]
    for t in tier_names():
        cfg = make_config(t)
        with open(os.path.join(ROOT, "configs", f"h3turbo-{t}.json"), "w") as f:
            json.dump(cfg.to_dict(), f, indent=1, sort_keys=True)
        p = estimate(cfg).params
        lines.append(
            f"| {t} | {p['transformer_total_M']:.0f} M | {p['on_gpu_M (no adaln)']:.0f} M | {p['adaln_M (kept on CPU)']:.0f} M | {p['text_encoder_M']:.0f} M | {p['video_vae_M']:.0f} M |"
        )
    for name, w, h, sec in CASES:
        lines += ["", f"## {name}, {STEPS} steps", "", "| tier | tokens | TFLOP / generation | GPU weights fp16 / int8 / int4 (GB) | + activations (GB) | lowest precision that fits (" + ", ".join(CARDS) + ") |", "|---|---|---|---|---|---|"]
        for t in tier_names():
            e = estimate(make_config(t), w, h, sec, STEPS)
            fit = []
            for c in CARDS:
                best = next((p for p in ("fp16", "int8", "int4") if e.fits(GPUS[c], p)), "offload")
                fit.append(best)
            wg = e.weights_gb
            lines.append(f"| {t} | {e.tokens['total']} | {e.generation_tflop:.0f} | {wg['fp16']:.2f} / {wg['int8']:.2f} / {wg['int4']:.2f} | {e.activations_gb:.2f} | {' / '.join(fit)} |")
    with open(os.path.join(ROOT, "docs", "SIZING.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
